# YAML file to specify the configuration of the DACs webhook
## Author: Huthayfa Patel

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration # specifies as validating webhook config
metadata:
  name: webhook-diss
webhooks:
  - name: webhook-server.webhook-diss.svc
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"] # specifies what versions of reviews can be used
    clientConfig:
      service:
        name: webhook-server
        namespace: dissertation
        path: "/"
      caBundle: ${CA_PEM_B64} # specifies use of ca crt
    # Details rules of DACs
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        
